{{ if .Values.policy.enabled }}
apiVersion: policy.sigstore.dev/v1alpha1
kind: ClusterImagePolicy
metadata:
  name: github-policy
spec:
  images: {{ include "clusterimagepolicy.images" . | nindent 4  }}
  authorities:
{{ if .Values.policy.trust.github }}
  - name: github
    keyless:
      trustRootRef: github
      url: https://fulcio.githubapp.com
      identities:
      - issuer: https://token.actions.githubusercontent.com
        {{- include "clusterimagepolicy.subjectRegExp" . | nindent 8 }}
    rfc3161timestamp:
      trustRootRef: github
    signatureFormat: bundle
    attestations:
    - name: require-attestation
      predicateType: {{ .Values.policy.predicateType }}
{{ end }}{{ if .Values.policy.trust.sigstorePublic }}
  - name: public-good
    keyless:
      identities:
      - issuer: https://token.actions.githubusercontent.com
        {{- include "clusterimagepolicy.subjectRegExp" . | nindent 8 }}
      url: https://fulcio.sigstore.dev
    ctlog:
      url: https://rekor.sigstore.dev
    signatureFormat: bundle
    attestations:
    - name: require-attestation
      predicateType: {{ .Values.policy.predicateType }}
{{ end }}
{{- end }}
