name: Test Charts

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
        with:
          version: v3.10.3

      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.13'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml

      - name: Create KIND Cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0

      - name: Install policy-controller
        run: |
          helm install policy-controller charts/policy-controller \
            --create-namespace --namespace artifact-attestations --atomic

      - name: Install trust-policies
        run: |
          helm install trust-policies charts/trust-policies \
            --set policy.enabled=true \
            --set policy.organization=github
